// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeuNCen0CrB1WNvVy2RvDyBIRdWr_RJ8g',
    appId: '1:937703255335:web:08aa17cbe9365014c88d02',
    messagingSenderId: '937703255335',
    projectId: 'minix-677e3',
    authDomain: 'minix-677e3.firebaseapp.com',
    storageBucket: 'minix-677e3.firebasestorage.app',
    measurementId: 'G-22H5Q8DF8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA58woroOr0ZZUgGIJEnQ5Yy5s8kWe3iC0',
    appId: '1:937703255335:android:cdbb8541e22c16ccc88d02',
    messagingSenderId: '937703255335',
    projectId: 'minix-677e3',
    storageBucket: 'minix-677e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEzAzC6l8lGeqLW_EFkADSraCyyC58hao',
    appId: '1:937703255335:ios:433625c84124f6c1c88d02',
    messagingSenderId: '937703255335',
    projectId: 'minix-677e3',
    storageBucket: 'minix-677e3.firebasestorage.app',
    iosBundleId: 'com.example.minix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEzAzC6l8lGeqLW_EFkADSraCyyC58hao',
    appId: '1:937703255335:ios:433625c84124f6c1c88d02',
    messagingSenderId: '937703255335',
    projectId: 'minix-677e3',
    storageBucket: 'minix-677e3.firebasestorage.app',
    iosBundleId: 'com.example.minix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeuNCen0CrB1WNvVy2RvDyBIRdWr_RJ8g',
    appId: '1:937703255335:web:be6da143ad4966ecc88d02',
    messagingSenderId: '937703255335',
    projectId: 'minix-677e3',
    authDomain: 'minix-677e3.firebaseapp.com',
    storageBucket: 'minix-677e3.firebasestorage.app',
    measurementId: 'G-085QPGXTGW',
  );
}
